### ISSUE TITLE
-utf8 not applied to filenames

### ISSUE THREAD

**Issue by akarelas** [ingydotnet/io-all-pm#95]
When I do:

``` perl
use IO::All -utf8;
my @filenames = io('dir')->all;
```

...then `@filenames` doesn't contain character strings, but byte strings.

**Comment by sesc** [comment]
I can confirm that.
The root cause is that IO::All::Dir uses the core module IO::Dir (which last was changed in 2003).

The following code replicates the basic operation found in IO::All::Dir, and the bug:
`perl -C -e 'use IO::Dir; my $h = IO::Dir->new; $h->open("."); while (my $n = $h->read) { print "$n\n" }'`

**Comment by sesc** [comment]
Here is a workaround, using the same `utf8::decode` IO::All already uses in its Tie functions:
`perl -C -e 'use IO::Dir; my $h = IO::Dir->new; $h->open("."); while (my $n = $h->read) { utf8::decode($n); print "$n\n" }'`
(Of course, the decoding must be made conditional upon the `-utf8` flag before we can try to have it included in the module.)

**Comment by akarelas** [comment]
Thanks for the pull request. You seem smart. Do you think you could also fix [this other utf8 issue](https://github.com/ingydotnet/io-all-pm/issues/93) ?

**Comment by sesc** [comment]
Thanks for your response!
I'll have a look at the other issue.
